
#echo "Downloading mogodb repo"
#curl -s -o /etc/yum.repos.d/mongodb.repo https://raw.githubusercontent.com/roboshop-devops-project/mongodb/main/mongo.repo &>>$LOG_FILE
#StatusCheck $?
#
#echo "Installing Mongodb package"
#yum install -y mongodb-org &>>$LOG_FILE
#StatusCheck $?
#
#echo "Updating Listen address in .conf file"
#sed -i -e 's/127.0.0.1/0.0.0.0/' /etc/mongod.conf
#StatusCheck $?
#
#echo "Enabling MOngodb service"
#systemctl enable mongod &>>$LOG_FILE
#StatusCheck $?
#
#echo "Restarting MOngodb Server"
#systemctl restart mongod &>>$LOG_FILE
#StatusCheck $?
#
#echo "Downloading Mongodb Schema files"
#curl -s -L -o /tmp/mongodb.zip "https://github.com/roboshop-devops-project/mongodb/archive/main.zip" &>>$LOG_FILE
#StatusCheck $?
#
#cd /tmp
#echo "Extracting mongobd schema files"
#unzip mongodb.zip &>>$LOG_FILE
#StatusCheck $?
#
#cd mongodb-main
#echo "Loading catalogue service schema"
#mongo < catalogue.js &>>$LOG_FILE
#StatusCheck $?
#
#echo "Loading user service schema"
#mongo < users.js &>>$LOG_FILE
#StatusCheck $?

- name: Setting up mongodb.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongoDB server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update MongoDB listen  address
  ansible.builtin.replace:
      path: /etc/hosts
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

- name: enable and restart mongod service
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Download and Unzip schema files
  ansible.builtin.unarchive:
      src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
      dest: /tmp
      remote_src: yes

#- name: Load schema files
#  community.mongodb.mongodb_shell:
#      file: ""
#      idempotent: yes
#
#- name: Run a js file containing MongoDB commands with pseudo-idempotency
#  community.mongodb.mongodb_shell:
#      login_user: user
#      login_password: secret
#      file: "/path/to/mongo/file.js"
#      idempotent: yes