#echo Starting Nginx Service
#systemctl enable nginx &>>LOG_FILE
#systemctl restart nginx &>>LOG_FILE
#StatusCheck $?

- name: Installing Nginx Server
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Remove previous files data
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Downloading Nginx web content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: copying files to the path
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copying conf to the roboshop.conf
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart Nginx Service

- name: enabling and restarting the service
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started