#COMPONENT=rabbitmq
#source common.sh
#LOG_FILE=/tmp/${COMPONENT}
#
#echo "Setup RabbitMQ Repos"
#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>$LOG_FILE
#StatusCheck $?
#
#echo "Install Erland & RabbitMQ"
#yum install https://github.com/rabbitmq/erlang-rpm/releases/download/v23.2.6/erlang-23.2.6-1.el7.x86_64.rpm rabbitmq-server -y &>>$LOG_FILE
#StatusCheck $?
#
#echo "Start RabbitMQ Server"
#systemctl enable rabbitmq-server &>>$LOG_FILE
#systemctl restart rabbitmq-server &>>$LOG_FILE
#StatusCheck $?
#
#rabbitmqctl  list_users | grep roboshop &>>$LOG_FILE
#if [ $? -ne 0 ]; then
#echo "Add Application USer in RabbitMQ"
#rabbitmqctl add_user roboshop roboshop123 &>>$LOG_FILE
#StatusCheck $?
#fi
#
#echo "Add Application USer tags in RabbitMQ"
#rabbitmqctl set_user_tags roboshop administrator &>>$LOG_FILE
#StatusCheck $?
#
#echo "Add permissions for App User in RabbitMQ"
#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"  &>>$LOG_FILE
#StatusCheck $?

- name: Configure rabbitmq server
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install Erlang and RabbitMQ
  ansible.builtin.yum:
    name: "{{item}}"
    state: installed
    disable_gpg_check: yes
  loop:
    - https://github.com/rabbitmq/erlang-rpm/releases/download/v25.1.1/erlang-25.1.1-1.el8.x86_64.rpm
    - rabbitmq-server

- name: enable and start rabbitMQ server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
    enabled: yes

- name: Adding roboshop user in rabbitmq
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{ROBOSHOP_RABBITMQ_PASSWORD}}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    tags: administrator
