- name: copy logstash conf
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start logstash service
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: wait for logstash service to start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 5044
    delay: 30
    timeout: 10
