- name: copy logstash conf
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start logstash service
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: wait for logstash service to start
  ansible.builtin.shell: sleep 60 && netstat -lntp | grep 5044
