#LOG_FILE=/tmp/mysql
#source common.sh

#echo "declaring the default password"
#DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | awk '{print $NF}')
#StatusCheck $?
#
#echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${ROBOSHOP_MYSQL_PASSWORD}');
#FLUSH PRIVILEGES;" >/tmp/root-pass.sql
#
#echo "show databases" |mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} &>>${LOG_FILE}
#if [ $? -ne 0 ]; then
#echo "Change the default password"
#mysql --connect-expired-password -uroot -p"${DEFAULT_PASSWORD}" </tmp/root-pass.sql &>>${LOG_FILE}
#StatusCheck $?
#fi
#
#echo 'show plugins' | mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} | grep 'validate_password' &>>${LOG_FILE}
#if [ $? -eq 0 ]; then
#echo "uninstall password plugin validation"
#echo "uninstall plugin validate_password;" | mysql -uroot -p${ROBOSHOP_MYSQL_PASSWORD} &>>${LOG_FILE}
#fi
#
#  # uninstall plugin validate_password;
#echo "download schema"
#curl -s -L -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysql/archive/main.zip" &>>${LOG_FILE}
#StatusCheck $?
#cd /tmp
#rm -rf mysql-main
#echo "extracting schema"
#unzip mysql.zip &>>${LOG_FILE}
#StatusCheck $?
#
#echo "load schema"
#cd mysql-main
#mysql -u root -p${ROBOSHOP_MYSQL_PASSWORD} <shipping.sql
#StatusCheck $?

- name: Copying repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disabling previous mysql modules
  ansible.builtin.shell: dnf module disable mysql -y

- name: Installing mysql server, devel package and python3 dependency packages
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
      - mysql-community-devel
      - mysql-community-server
      - gcc
      - python36-devel

- name: enable and restarting mysql server
  ansible.builtin.systemd:
    name: mysqld
    enabled: yes
    state: started

- name: Load mysql log file
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: out
# to fetch the default password

- name: Install mysql pip3 client
  ansible.builtin.pip:
    name: mysqlclient
    executable: pip3

# running mysql queries using ansible
- name: Check mysql credentials
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ROBOSHOP_MYSQL_PASSWORD}}"
    filter: version
  ignore_errors: yes
  register: mysql_conn_status

- name: copy sql file to reset password
  ansible.builtin.template:
    src: reset-root-pass.sql
    dest: /tmp/root-pass.sql
  when: mysql_conn_status is failed

- name: Change the password
  ansible.builtin.shell: mysql --connect-expired-password -uroot -p"{{ out['content'] | b64decode | regex_findall('A temporary password.*') | join (' ') | split (' ') | last }}" </tmp/root-pass.sql
  when: mysql_conn_status is failed

- name: validating password plugin
  community.mysql.mysql_query:
    query: 'show plugins'
    login_user: root
    login_password: "{{ROBOSHOP_MYSQL_PASSWORD}}"
    filter: version
  ignore_errors: yes
  register: plugins_status

- name: print plugins_status
  ansible.builtin.debug:
    msg: "{{plugins_status | regex_findall('validate_password') | length}}"

