- name: Installing golang module
  ansible.builtin.yum:
    name: golang
    state: installed

- name: Adding Roboshop user
  ansible.builtin.user:
    name: roboshop

- name: clearing all the previous files
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Downloading app code
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: moving the code to specified path
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
  become_user: roboshop

- name: setting up dispatch service
  ansible.builtin.shell: go mod init dispatch; go get /home/ronoshop/{{COMPONENT}}/main.go