- name: copy prometheus config file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: wait for prometheus server to start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 30

