- name: copy prometheus config file
  ansible.builtin.template:
    src: "{{item}}"
    dest: /opt/prometheus/{{item}}
  loop:
    - prometheus.yml
    - record-rules.yml
    - alert-rules.yml

- name: Restart prometheus server
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: wait for prometheus server to start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9090
    delay: 10
    timeout: 30

- name: Alertmanager config  file
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alalertmanager.yml

- name: Restart alert manager service
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: wait for alert manager service to start
  ansible.builtin.wait_for:
    host: 0.0.0.0
    port: 9093
    delay: 10
    timeout: 30