- name: Download pyhon devel, python and gcc
  ansible.builtin.yum:
    name:
      - python36
      - python36-devel
      - gcc
    state: installed

- name: Import app-prereq task
  ansible.builtin.import_tasks: app-prereq.yml

- name: Installing PIP requirements for the file
  ansible.builtin.pip:
    requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
    executable: pip3

- name: Change UID & GID in App configuration
  ansible.builtin.lineinfile:
    path: /home/roboshop/{{COMPONENT}}/{{COMPONENT}}.ini
    regexp: '^{{item.name}}'
    line: "{{item.name}} = {{item.id}}"
  loop:
    - { name: "uid" , id: "{{appuser.uid}}"}
    - { name: "gid" , id: "{{appuser.group}}"}

- name: Import system-setup task
  ansible.builtin.import_tasks: system-setup.yml