
- name: Copy systemd file into new path
  ansible.builtin.template:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Reload and restarting the service/ setting up the service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}.service"
    state: restarted
    daemon_reload: yes
    enabled: yes