groups:
  - name: Alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          {% raw %}summary: "Instance Down - [{{ $labels.instance }}]"{% endraw %}

          {% raw %}description: "Instance Down - [{{ $labels.instance }}]"{% endraw %}

      - alert: MemoryHighUsage
        expr: node_memory_used_percent > 80
        labels:
          severity: critical
        annotations:
          {% raw %}summary: "High Memory Usage - [{{ $labels.Name }}]"{% endraw %}

          {% raw %}description: "High Memory Usage - [{{ $labels.Name }}]\n Private IP Address = [{{ $labels.Name }}]"{% endraw %}
  {% for component in components %}
      - alert: SeviceDown
        expr: node_systemd_unit_state{name="{{component}}.service",state="active"} < 1
        labels:
          severity: critical
        annotations:
          summary: "{{component}} Service Down -{% raw %} [{{ $labels.Name }}]"{% endraw %}

          description: "{{component}} Service Down -{% raw %} [{{ $labels.Name }}]\n Private IP Address = [{{ $labels.Name }}]"{% endraw %}

  {% endfor %}



